graph TD
    A[start] --> B1(登录请求) 
    A[start] --> B2(一般请求) 
    A[start] --> B3(登出请求)
    B1 --> C1(申请token)
    B2 --> C2{token是否失效}
    B3 --> C3(吊销token)

    C2 -->|是| B1
    C2 -->|否| D[校验token] --> E{是否通过}

    E --> |通过| F1(请求目标接口)
    E --> |不通过| F2(拦截请求)
    F1 --> G(返回结果) 
    F2 --> G
    C1 --> G
    C3 --> G
    G --> H[end]



