graph TD
    A[start] --> B(登录) 
    B --> C(申请token) --> C1(一般请求)
    C --> C2(登出请求) --> C21(吊销token)
    C1 --> D{token是否失效}
    D -->|是| B 
    D -->|否| F[校验token] --> G{是否通过}
    G --> |通过| G1(请求目标接口)
    G --> |不通过| G2(拒绝请求)
    G1 --> H(返回结果) 
    G2 --> H 
    C21 -->H
    H --> K(结束)


