graph LR
    A[start] --> B(mq消费消息)
    B --> C{判断任务<br/>类型}
    C -->|归集任务| C1(调用周期任务<br/>接口,创建任务)
    C -->|周期任务| C1(调用周期任务<br/>接口,创建任务)
    C -->|一次性任务| C2(调用一次性<br/>任务接口,<br/>创建任务) --> K(任务执行状态<br/>设为取消)

    C1 --> D(调用预约<br/>任务接口)
    K --> D(调用预约<br/>任务接口)

    D --> E(任务执行记录表<br/>记录任务) --> F[结束]


