graph LR
    A[start] --> B(任务扫描)
    B --> W{任务状态<br/>是否正常}
    W --> |是| Y1(调度任务)
    W --> |否| Y2(取消调度) --> B

    Y1 --> C1(一次性任务<br/>执行) --> D(获取数据库<br/>节点信息) --> E(调用kettle接口<br/>传输数据) --> U{是否是<br/>一次性任务} 
    
    U --> |是| F1(将所关联周期<br/>任务的执行<br/>状态设置为正常) --> X(更新任务执行<br/>记录表状态)
    U --> |否| X(更新任务执行<br/>记录表状态)
    
    Y1 --> H(周期性任务<br/>执行) --> D(获取数据库<br/>节点信息)

    X --> Y(发送消息)

    Y --> Z[end]
